version: "3.1"

services:
  localstack:
    container_name: "consortium-app"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=FAKE
      - AWS_SECRET_ACCESS_KEY=FAKE
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-scripts:/docker-entrypoint-initaws.d